### ISSUE TITLE
Failed to lookup view "error" in views directory

### ISSUE THREAD

**Issue by rnagara** [martiros/xss-spy#1]
Hi @martiros,

After follow the readme when I open the page http://localhost:3000/

with this error from console (thought I could get away with adding `views` directory but not 😅)
```
➜  xss-spy git:(master) ✗ npm start

> xss-spy@0.0.0 start /webroot/practicegenius/rnagara/xss-spy
> node ./bin/www

a user connected
user disconnected
GET / 200 6.290 ms - 474
GET /stylesheets/style.css 200 4.104 ms - 1458
GET /js/dashboard.js 200 2.184 ms - 4133
a user connected
GET /favicon.ico 404 276.031 ms - 1393
Error: Failed to lookup view "error" in views directory "/webroot/practicegenius/rnagara/xss-spy/views"
    at Function.render (/webroot/practicegenius/rnagara/xss-spy/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/webroot/practicegenius/rnagara/xss-spy/node_modules/express/lib/response.js:1008:7)
    at /webroot/practicegenius/rnagara/xss-spy/app.js:36:7
    at Layer.handle_error (/webroot/practicegenius/rnagara/xss-spy/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/webroot/practicegenius/rnagara/xss-spy/node_modules/express/lib/router/index.js:315:13)
    at /webroot/practicegenius/rnagara/xss-spy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/webroot/practicegenius/rnagara/xss-spy/node_modules/express/lib/router/index.js:335:12)
    at next (/webroot/practicegenius/rnagara/xss-spy/node_modules/express/lib/router/index.js:275:10)
    at /webroot/practicegenius/rnagara/xss-spy/app.js:25:3
    at Layer.handle [as handle_request] (/webroot/practicegenius/rnagara/xss-spy/node_modules/express/lib/router/layer.js:95:5)
```
<img width="1112" alt="screen shot 2018-11-12 at 7 53 16 am" src="https://user-images.githubusercontent.com/345010/48358649-1215f080-e650-11e8-9d12-2a14a1cf83a3.png">

(my node -v is 8.11.1 and npm -v is 5.6.0)

**Comment by rnagara** [comment]
this is my local issue, closing this out 😉
